language: node_js
node_js:
  - "10.16.3"

branches:
  only:
    - master
    - dev

install:
  - npm install

before_script:
  - npm install -g ionic cordova

script:
  - ionic cordova build browser --confirm --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  keep-history: true
  on:
    branch: master
  local_dir: www
