dist: trusty
sudo: false

language: node_js
node_js:
  - "10.16.3"

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - npm install -g ionic cordova

script:
  - ng test --watch false --browsers ChromeHeadless
  - ionic cordova build browser --confirm --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard
  keep-history: true
  on:
    branch: master
  local_dir: www
